export const SELECTTODOLIST: SELECTTODOLIST = 'SELECTTODOLIST';
export const SETTODOS: SETTODOS = 'SETTODOS';
export const SETTODOLISTS: SETTODOLISTS = 'SETTODOLISTS';
export const SETUSER: SETUSER = 'SETUSER';
export const LOGOUTUSER: LOGOUTUSER = 'LOGOUTUSER';
