export const SETTODOS: SETTODOS = 'SETTODOS';
export const CREATETODO: CREATETODO = 'CREATETODO';
export const EDITTODO: EDITTODO = 'EDITTODO';
export const TOGGLETODO: TOGGLETODO = 'TOGGLETODO';
export const DELETETODO: DELETETODO = 'DELETETODO';

export const SELECTTODOLIST: SELECTTODOLIST = 'SELECTTODOLIST';
export const CREATETODOLIST: CREATETODOLIST = 'CREATETODOLIST';
export const DELETETODOLIST: DELETETODOLIST = 'DELETETODOLIST';
