export const CREATETODO: CREATETODO = 'CREATETODO';
export const DELETETODO: DELETETODO = 'DELETETODO';
export const EDITTODO: EDITTODO = 'EDITTODO';
export const SETTODOS: SETTODOS = 'SETTODOS';
export const TOGGLETODO: TOGGLETODO = 'TOGGLETODO';

export const CREATETODOLIST: CREATETODOLIST = 'CREATETODOLIST';
export const DELETETODOLIST: DELETETODOLIST = 'DELETETODOLIST';
export const SELECTTODOLIST: SELECTTODOLIST = 'SELECTTODOLIST';
export const SETTODOLISTS: SETTODOLISTS = 'SETTODOLISTS';

export const LOGOUTUSER: LOGOUTUSER = 'LOGOUTUSER';
export const SETUSER: SETUSER = 'SETUSER';
